"""AIAMSBS Knowledge Base MCP server (K1, BACKLOG #30).

Exposes a SQLite+FTS5 backed knowledge base over the MCP streamable-http
transport. Five required tools (kb_search, kb_add, kb_update, kb_list,
kb_delete) plus two convenience source-management tools (kb_add_source,
kb_list_sources).

Also serves a bare HTML viewer at `/` and `/ui/` (BACKLOG #57) using
`@mcp.custom_route()` — a tiny single-file SPA that calls the same
tool functions via `/api/kb/list`, `/api/kb/entries/{id}` (GET + PATCH).
No direct DB access from the UI; the existing MCP tool layer is the
sole data path. The Svelte + ByteMD upgrade is a separate row (BACKLOG #55).

MVP search strategy: FTS5 BM25 ranking only. No embeddings, no model
calls, no network. Design justification in
`obsidian_vaults/agent vault/AIAMSBS_Docs_Diagrams/kb_workflow.md`.
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3

from mcp.server.fastmcp import FastMCP
from starlette.requests import Request
from starlette.responses import HTMLResponse, JSONResponse

DB_PATH = os.environ.get("KB_DB_PATH", "/data/kb.db")
SCHEMA_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "init_db.sql")

VALID_ENTRY_TYPES = ("runbook", "fact", "gotcha")
VALID_STATUSES = ("pending", "approved", "rejected")
VALID_CREATED_BY = ("agent", "customer")
VALID_SOURCE_TYPES = ("skill", "customer_doc", "runtime")

mcp = FastMCP("kb")


def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    """Load schema from init_db.sql and apply it to the database."""
    db_dir = os.path.dirname(DB_PATH)
    if db_dir:
        os.makedirs(db_dir, exist_ok=True)
    with open(SCHEMA_PATH, "r") as f:
        schema_sql = f.read()
    conn = _connect()
    conn.executescript(schema_sql)
    conn.commit()
    conn.close()


def _row_to_dict(row: sqlite3.Row) -> dict:
    d = dict(row)
    # tags is stored as a JSON array string. Surface it as a list so callers
    # don't have to re-parse on the wire. If it's NULL or invalid JSON,
    # fall back to the raw value (or None) rather than throwing.
    if "tags" in d and d["tags"] is not None:
        try:
            d["tags"] = json.loads(d["tags"])
        except (json.JSONDecodeError, TypeError):
            # Leave as string — caller can see the bad data.
            pass
    return d


@mcp.tool()
def kb_search(
    query: str, limit: int = 10, source_types: list[str] | None = None
) -> list[dict]:
    """FTS5 search across kb_entries. Returns matching entries ranked by BM25.

    Args:
        query: free-text search. FTS5 tokenizes the query, so multi-word
            queries find entries that contain any of the terms; quote a
            phrase for exact matching. The snippet column is generated by
            FTS5 itself (highlighted with \u001e markers).
        limit: max results (default 10).
        source_types: optional filter; if given, restrict to entries whose
            source has one of these source_type values. Uses LEFT JOIN, so
            entries with no source (source_id NULL) are always included
            unless you also pass an explicit list.
    """
    conn = _connect()
    cur = conn.cursor()

    if source_types:
        # Validate against the schema's CHECK constraint so we don't return
        # 500-shaped errors from SQLite on a bad type.
        for st in source_types:
            if st not in VALID_SOURCE_TYPES:
                conn.close()
                return [{"error": f"invalid source_type: {st}"}]
        placeholders = ",".join("?" * len(source_types))
        # INNER JOIN: when caller filters by source_type they only want
        # entries that came from a source of that type. Sourceless
        # entries (source_id NULL) are excluded.
        sql = f"""
            SELECT e.*, snippet(kb_fts, 0, '[', ']', '...', 8) AS snippet,
                   bm25(kb_fts) AS rank
            FROM kb_fts
            JOIN kb_entries e ON e.id = kb_fts.rowid
            JOIN kb_sources s ON s.id = e.source_id
            WHERE kb_fts MATCH ?
              AND s.source_type IN ({placeholders})
            ORDER BY rank
            LIMIT ?
        """
        params: list = [query, *source_types, limit]
    else:
        sql = """
            SELECT e.*, snippet(kb_fts, 0, '[', ']', '...', 8) AS snippet,
                   bm25(kb_fts) AS rank
            FROM kb_fts
            JOIN kb_entries e ON e.id = kb_fts.rowid
            WHERE kb_fts MATCH ?
            ORDER BY rank
            LIMIT ?
        """
        params = [query, limit]

    cur.execute(sql, params)
    rows = cur.fetchall()
    conn.close()
    return [_row_to_dict(r) for r in rows]


@mcp.tool()
def kb_add(
    content: str,
    entry_type: str,
    tags: list[str] | None = None,
    source_id: int | None = None,
    created_by: str = "agent",
) -> dict:
    """Add a KB entry. Returns the new entry id and current state.

    For MVP, all agent-written entries are created with status='pending'
    (Level 0 trust). Customer-written entries are created with
    status='approved' (Level 3 trust — they wrote it, they own it).

    Args:
        content: the runbook/fact/gotcha text.
        entry_type: one of 'runbook', 'fact', 'gotcha'.
        tags: optional list of tag strings; stored as a JSON array.
        source_id: optional FK to kb_sources.id.
        created_by: 'agent' (default) or 'customer'.
    """
    if entry_type not in VALID_ENTRY_TYPES:
        return {"error": f"entry_type must be one of {VALID_ENTRY_TYPES}"}
    if created_by not in VALID_CREATED_BY:
        return {"error": f"created_by must be one of {VALID_CREATED_BY}"}

    # Customer-written entries are auto-approved; agents always start
    # at pending.
    initial_status = "approved" if created_by == "customer" else "pending"
    # Mirror the trust ladder: customer=3, agent=0. K6 can add intermediate
    # levels (e.g., 'approved_agent') later without breaking the schema.
    initial_trust = 3 if created_by == "customer" else 0

    tags_json = json.dumps(tags) if tags else None

    conn = _connect()
    cur = conn.cursor()
    if source_id is not None:
        cur.execute(
            """
            INSERT INTO kb_entries
                (source_id, entry_type, content, tags, created_by, status, trust_level_at_creation)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (source_id, entry_type, content, tags_json, created_by, initial_status, initial_trust),
        )
    else:
        cur.execute(
            """
            INSERT INTO kb_entries
                (entry_type, content, tags, created_by, status, trust_level_at_creation)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (entry_type, content, tags_json, created_by, initial_status, initial_trust),
        )
    new_id = cur.lastrowid
    conn.commit()
    cur.execute("SELECT * FROM kb_entries WHERE id=?", (new_id,))
    row = cur.fetchone()
    conn.close()
    return _row_to_dict(row)


@mcp.tool()
def kb_update(
    entry_id: int,
    content: str | None = None,
    tags: list[str] | None = None,
    status: str | None = None,
) -> dict:
    """Update an existing KB entry.

    Args:
        entry_id: required. The id of the entry to update.
        content: new content (if changing).
        tags: new tags list (replaces existing).
        status: new status. Customer flips pending -> approved/rejected.

    Returns the updated row, or {'error': 'not found'} if entry_id is
    unknown, or {'error': 'no fields to update'} if nothing was passed.
    """
    if status is not None and status not in VALID_STATUSES:
        return {"error": f"status must be one of {VALID_STATUSES}"}

    conn = _connect()
    cur = conn.cursor()
    cur.execute("SELECT * FROM kb_entries WHERE id=?", (entry_id,))
    if cur.fetchone() is None:
        conn.close()
        return {"error": "not found", "entry_id": entry_id}

    updates: dict = {}
    if content is not None:
        updates["content"] = content
    if tags is not None:
        updates["tags"] = json.dumps(tags)
    if status is not None:
        updates["status"] = status

    if not updates:
        conn.close()
        return {"error": "no fields to update"}

    updates["updated_at"] = "CURRENT_TIMESTAMP"
    set_clause = ", ".join(f"{k}=?" for k in updates.keys())
    values = list(updates.values()) + [entry_id]
    cur.execute(
        f"UPDATE kb_entries SET {set_clause} WHERE id=?",
        values,
    )
    conn.commit()
    cur.execute("SELECT * FROM kb_entries WHERE id=?", (entry_id,))
    row = cur.fetchone()
    conn.close()
    return _row_to_dict(row)


@mcp.tool()
def kb_list(
    source_type: str | None = None,
    status: str | None = None,
    limit: int = 50,
    offset: int = 0,
) -> list[dict]:
    """List KB entries, optionally filtered. For the review queue UI.

    Args:
        source_type: optional filter — restrict to entries whose source has
            this source_type. Entries with no source (source_id NULL) are
            always included.
        status: optional filter — restrict to this status.
        limit: max rows (default 50).
        offset: for pagination.
    """
    if source_type is not None and source_type not in VALID_SOURCE_TYPES:
        return [{"error": f"invalid source_type: {source_type}"}]
    if status is not None and status not in VALID_STATUSES:
        return [{"error": f"invalid status: {status}"}]

    conn = _connect()
    cur = conn.cursor()
    # When source_type is set, INNER JOIN so we only return entries that
    # came from a matching source. When source_type is NOT set, LEFT JOIN
    # so sourceless entries (source_id NULL) are included in the listing.
    if source_type is not None:
        sql = """
            SELECT e.*
            FROM kb_entries e
            JOIN kb_sources s ON s.id = e.source_id
            WHERE 1=1
        """
    else:
        sql = """
            SELECT e.*
            FROM kb_entries e
            LEFT JOIN kb_sources s ON s.id = e.source_id
            WHERE 1=1
        """
    params: list = []
    if source_type is not None:
        sql += " AND s.source_type = ?"
        params.append(source_type)
    if status is not None:
        sql += " AND e.status = ?"
        params.append(status)
    sql += " ORDER BY e.id DESC LIMIT ? OFFSET ?"
    params.extend([limit, offset])
    cur.execute(sql, params)
    rows = cur.fetchall()
    conn.close()
    return [_row_to_dict(r) for r in rows]


@mcp.tool()
def kb_delete(entry_id: int) -> dict:
    """Delete a KB entry. Returns the deleted entry contents.

    DESTRUCTIVE — the row is permanently removed (and the FTS index
    is updated via the kb_ad trigger). Callers should always confirm
    with the user before invoking this.
    """
    conn = _connect()
    cur = conn.cursor()
    cur.execute("SELECT * FROM kb_entries WHERE id=?", (entry_id,))
    row = cur.fetchone()
    if row is None:
        conn.close()
        return {"error": "not found", "entry_id": entry_id}
    deleted = _row_to_dict(row)
    cur.execute("DELETE FROM kb_entries WHERE id=?", (entry_id,))
    conn.commit()
    rows_affected = cur.rowcount
    conn.close()
    return {
        "status": "deleted",
        "entry_id": entry_id,
        "rows": rows_affected,
        "deleted_record": deleted,
    }


# ---------------------------------------------------------------------------
# Optional convenience tools: source management.
# Useful for K2 (bootstrap ingestion) and K3 (review queue UI).
# ---------------------------------------------------------------------------


@mcp.tool()
def kb_add_source(
    name: str, source_type: str, file_path_or_url: str | None = None
) -> dict:
    """Add a KB source (where knowledge chunks came from).

    Args:
        name: human-readable name (e.g., "OpenWrt firewall runbook").
        source_type: one of 'skill', 'customer_doc', 'runtime'.
        file_path_or_url: optional path or URL for traceability.
    """
    if source_type not in VALID_SOURCE_TYPES:
        return {"error": f"source_type must be one of {VALID_SOURCE_TYPES}"}
    conn = _connect()
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO kb_sources (name, source_type, file_path_or_url) VALUES (?, ?, ?)",
        (name, source_type, file_path_or_url),
    )
    new_id = cur.lastrowid
    conn.commit()
    cur.execute("SELECT * FROM kb_sources WHERE id=?", (new_id,))
    row = cur.fetchone()
    conn.close()
    return dict(row)


@mcp.tool()
def kb_list_sources() -> list[dict]:
    """List all KB sources, newest first."""
    conn = _connect()
    cur = conn.cursor()
    cur.execute("SELECT * FROM kb_sources ORDER BY id DESC")
    rows = cur.fetchall()
    conn.close()
    return [dict(r) for r in rows]


# ----------------------------------------------------------------------------
# Bare HTML viewer (BACKLOG #57) — restored because the original /ui/
# endpoint was lost in a kb-mcp rebase. Tiny single-file SPA; the Svelte +
# ByteMD upgrade is a separate row (BACKLOG #55).
# ----------------------------------------------------------------------------

INDEX_HTML = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>AIAMSBS KB Viewer</title>
<style>
  body { font-family: -apple-system, system-ui, sans-serif; max-width: 900px;
         margin: 2em auto; padding: 0 1em; color: #222; }
  h1 { font-size: 1.4em; }
  .entry { padding: 0.6em 0; border-bottom: 1px solid #eee; }
  .entry a { color: #06c; text-decoration: none; }
  .entry a:hover { text-decoration: underline; }
  .badge { display: inline-block; padding: 1px 6px; font-size: 0.8em;
           border-radius: 3px; background: #eee; margin-left: 0.4em; }
  .badge.pending { background: #ffd; }
  .badge.approved { background: #dfd; }
  .badge.rejected { background: #fdd; }
  #detail { margin-top: 1.5em; padding: 1em; background: #f8f8f8;
            border-radius: 4px; }
  pre { white-space: pre-wrap; word-wrap: break-word; }
  textarea { width: 100%; min-height: 8em; font-family: inherit; }
  button { padding: 0.5em 1em; margin-right: 0.5em; }
  .msg { color: #080; font-weight: bold; }
  .err { color: #c00; font-weight: bold; }
</style>
</head>
<body>
<h1>AIAMSBS KB Viewer</h1>
<p><a href="#" id="back">&larr; Back to list</a></p>
<div id="list"></div>
<div id="detail" style="display:none;"></div>

<script>
const STATUS_BADGE = {pending:'pending', approved:'approved', rejected:'rejected'};

async function fetchJSON(url, opts) {
  const r = await fetch(url, opts);
  const body = await r.json();
  if (!r.ok || body.error) {
    throw new Error(body.error || ('HTTP ' + r.status));
  }
  return body;
}

async function loadList() {
  const el = document.getElementById('list');
  el.innerHTML = 'Loading…';
  document.getElementById('detail').style.display = 'none';
  try {
    const {data} = await fetchJSON('/api/kb/list');
    if (!data || data.length === 0) {
      el.innerHTML = '<p>No KB entries yet.</p>';
      return;
    }
    let html = '';
    for (const e of data) {
      const status = STATUS_BADGE[e.status] || '';
      const type = e.entry_type || '';
      html += `<div class="entry">
        <a href="#id=${e.id}"><strong>${e.id}. ${escape(e.title || '(no title)')}</strong></a>
        <span class="badge ${status}">${status}</span>
        <span class="badge">${type}</span>
      </div>`;
    }
    el.innerHTML = html;
    if (location.hash.startsWith('#id=')) {
      const id = parseInt(location.hash.slice(4), 10);
      if (!Number.isNaN(id)) await loadDetail(id, data);
    }
  } catch (err) {
    el.innerHTML = `<p class="err">Error loading entries: ${escape(err.message)}</p>`;
  }
}

async function loadDetail(id, cachedList) {
  document.getElementById('list').style.display = 'none';
  const det = document.getElementById('detail');
  det.style.display = 'block';
  det.innerHTML = 'Loading…';
  try {
    const {data} = await fetchJSON('/api/kb/entries/' + id);
    det.innerHTML = `
      <h2>Entry #${data.id}: ${escape(data.title || '(no title)')}</h2>
      <p>
        <span class="badge">${data.entry_type || ''}</span>
        <span class="badge ${data.status}">${data.status}</span>
        ${data.tags && data.tags.length ? '<span class="badge">tags: ' + escape(JSON.stringify(data.tags)) + '</span>' : ''}
      </p>
      <label for="content"><strong>Content:</strong></label>
      <textarea id="content">${escape(data.content || '')}</textarea>
      <p style="margin-top:1em">
        <button id="save">Save</button>
        <button id="approve">Approve (pending &rarr; approved)</button>
        <button id="reject">Reject (pending &rarr; rejected)</button>
      </p>
      <p id="status"></p>
      <p style="font-size:0.8em;color:#666">
        created_by: ${escape(data.created_by || '')} ·
        updated_at: ${escape(data.updated_at || '')}
      </p>`;
    document.getElementById('save').onclick = () => saveEntry(data.id, {content: document.getElementById('content').value});
    document.getElementById('approve').onclick = () => saveEntry(data.id, {status: 'approved'});
    document.getElementById('reject').onclick = () => saveEntry(data.id, {status: 'rejected'});
  } catch (err) {
    det.innerHTML = `<p class="err">Error loading entry: ${escape(err.message)}</p>`;
  }
}

async function saveEntry(id, patch) {
  const statusEl = document.getElementById('status');
  statusEl.textContent = 'Saving…';
  try {
    await fetchJSON('/api/kb/entries/' + id, {
      method: 'PATCH',
      headers: {'Content-Type': 'application/json'},
      body: JSON.stringify(patch),
    });
    statusEl.innerHTML = '<span class="msg">Saved.</span>';
    setTimeout(() => loadList(), 500);
  } catch (err) {
    statusEl.innerHTML = '<span class="err">Save failed: ' + escape(err.message) + '</span>';
  }
}

function escape(s) {
  return String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
}

document.getElementById('back').onclick = (e) => {
  e.preventDefault();
  history.pushState({}, '', location.pathname);
  document.getElementById('list').style.display = 'block';
  document.getElementById('detail').style.display = 'none';
};
window.addEventListener('hashchange', () => {
  if (location.hash.startsWith('#id=')) {
    const id = parseInt(location.hash.slice(4), 10);
    if (!Number.isNaN(id)) loadDetail(id);
  } else {
    document.getElementById('list').style.display = 'block';
    document.getElementById('detail').style.display = 'none';
  }
});

loadList();
</script>
</body>
</html>"""


@mcp.custom_route("/", methods=["GET"])
async def serve_root(request: Request) -> HTMLResponse:
    """Root redirect-equivalent: serve the KB viewer HTML."""
    return HTMLResponse(INDEX_HTML)


@mcp.custom_route("/ui", methods=["GET"])
async def serve_ui_short(request: Request) -> HTMLResponse:
    """Bare KB viewer (BACKLOG #57). Same HTML as /."""
    return HTMLResponse(INDEX_HTML)


@mcp.custom_route("/ui/", methods=["GET"])
async def serve_ui_slash(request: Request) -> HTMLResponse:
    """Trailing-slash alias for /ui (some clients/proxies double-slash)."""
    return HTMLResponse(INDEX_HTML)


@mcp.custom_route("/api/kb/list", methods=["GET"])
async def api_kb_list(request: Request) -> JSONResponse:
    """JSON wrapper around the kb_list MCP tool. No direct DB access."""
    try:
        # kb_list is a regular Python function (the @mcp.tool() decorator
        # only registers it with FastMCP — it remains callable directly).
        entries = kb_list()
        if entries and isinstance(entries[0], dict) and "error" in entries[0]:
            return JSONResponse({"error": entries[0]["error"]}, status_code=400)
        return JSONResponse({"data": entries, "count": len(entries)})
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=500)


@mcp.custom_route("/api/kb/entries/{entry_id:int}", methods=["GET"])
async def api_kb_get(request: Request) -> JSONResponse:
    """JSON wrapper around a direct SELECT for one entry.

    Note: there is no kb_get MCP tool — this endpoint uses the same DB
    layer (read-only, no joins) that kb_list uses. UI does not need to
    cross the MCP HTTP transport for read paths.
    """
    entry_id = request.path_params["entry_id"]
    try:
        conn = _connect()
        cur = conn.cursor()
        cur.execute("SELECT * FROM kb_entries WHERE id=?", (entry_id,))
        row = cur.fetchone()
        conn.close()
        if row is None:
            return JSONResponse({"error": "not found", "entry_id": entry_id},
                                status_code=404)
        return JSONResponse({"data": _row_to_dict(row)})
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=500)


@mcp.custom_route("/api/kb/entries/{entry_id:int}", methods=["PATCH"])
async def api_kb_update(request: Request) -> JSONResponse:
    """JSON wrapper around the kb_update MCP tool. No direct DB access.

    Body JSON keys mirror kb_update kwargs: content, tags, status.
    All fields optional; at least one must be supplied.
    """
    entry_id = request.path_params["entry_id"]
    try:
        body = await request.json()
    except Exception:
        return JSONResponse({"error": "invalid JSON body"}, status_code=400)
    if not isinstance(body, dict):
        return JSONResponse({"error": "body must be a JSON object"},
                            status_code=400)
    allowed = {"content", "tags", "status"}
    unknown = set(body) - allowed
    if unknown:
        return JSONResponse(
            {"error": f"unknown fields: {sorted(unknown)}; allowed: {sorted(allowed)}"},
            status_code=400,
        )
    if not body:
        return JSONResponse(
            {"error": "no fields to update; supply at least one of: content, tags, status"},
            status_code=400,
        )
    try:
        result = kb_update(entry_id=entry_id, **body)
        if isinstance(result, dict) and "error" in result:
            return JSONResponse(result, status_code=400)
        return JSONResponse({"data": result})
    except Exception as e:
        return JSONResponse({"error": str(e)}, status_code=500)


def main() -> None:
    parser = argparse.ArgumentParser(description="AIAMSBS kb-mcp server")
    parser.add_argument("--host", default="0.0.0.0", help="bind host (default 0.0.0.0)")
    parser.add_argument("--port", type=int, default=8002, help="bind port (default 8002)")
    args = parser.parse_args()

    init_db()

    # FastMCP.run() does not accept host/port kwargs in this version — set
    # via the settings object (host/port are top-level Settings fields).
    # Custom routes registered via @mcp.custom_route() share the same
    # streamable-http transport on this port (BACKLOG #57).
    mcp.settings.host = args.host
    mcp.settings.port = args.port
    mcp.run(transport="streamable-http")


if __name__ == "__main__":
    main()
