"""AIAMSBS Knowledge Base MCP server (K1, BACKLOG #30).

Exposes a SQLite+FTS5 backed knowledge base over the MCP streamable-http
transport. Five required tools (kb_search, kb_add, kb_update, kb_list,
kb_delete) plus two convenience source-management tools (kb_add_source,
kb_list_sources).

MVP search strategy: FTS5 BM25 ranking only. No embeddings, no model
calls, no network. Design justification in
`obsidian_vaults/agent vault/AIAMSBS_Docs_Diagrams/kb_workflow.md`.
"""

from __future__ import annotations

import argparse
import json
import os
import sqlite3

from mcp.server.fastmcp import FastMCP

DB_PATH = os.environ.get("KB_DB_PATH", "/data/kb.db")
SCHEMA_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "init_db.sql")

VALID_ENTRY_TYPES = ("runbook", "fact", "gotcha")
VALID_STATUSES = ("pending", "approved", "rejected")
VALID_CREATED_BY = ("agent", "customer")
VALID_SOURCE_TYPES = ("skill", "customer_doc", "runtime")

mcp = FastMCP("kb")


def _connect() -> sqlite3.Connection:
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


def init_db() -> None:
    """Load schema from init_db.sql and apply it to the database."""
    db_dir = os.path.dirname(DB_PATH)
    if db_dir:
        os.makedirs(db_dir, exist_ok=True)
    with open(SCHEMA_PATH, "r") as f:
        schema_sql = f.read()
    conn = _connect()
    conn.executescript(schema_sql)
    conn.commit()
    conn.close()


def _row_to_dict(row: sqlite3.Row) -> dict:
    d = dict(row)
    # tags is stored as a JSON array string. Surface it as a list so callers
    # don't have to re-parse on the wire. If it's NULL or invalid JSON,
    # fall back to the raw value (or None) rather than throwing.
    if "tags" in d and d["tags"] is not None:
        try:
            d["tags"] = json.loads(d["tags"])
        except (json.JSONDecodeError, TypeError):
            # Leave as string — caller can see the bad data.
            pass
    return d


@mcp.tool()
def kb_search(
    query: str, limit: int = 10, source_types: list[str] | None = None
) -> list[dict]:
    """FTS5 search across kb_entries. Returns matching entries ranked by BM25.

    Args:
        query: free-text search. FTS5 tokenizes the query, so multi-word
            queries find entries that contain any of the terms; quote a
            phrase for exact matching. The snippet column is generated by
            FTS5 itself (highlighted with \u001e markers).
        limit: max results (default 10).
        source_types: optional filter; if given, restrict to entries whose
            source has one of these source_type values. Uses LEFT JOIN, so
            entries with no source (source_id NULL) are always included
            unless you also pass an explicit list.
    """
    conn = _connect()
    cur = conn.cursor()

    if source_types:
        # Validate against the schema's CHECK constraint so we don't return
        # 500-shaped errors from SQLite on a bad type.
        for st in source_types:
            if st not in VALID_SOURCE_TYPES:
                conn.close()
                return [{"error": f"invalid source_type: {st}"}]
        placeholders = ",".join("?" * len(source_types))
        # INNER JOIN: when caller filters by source_type they only want
        # entries that came from a source of that type. Sourceless
        # entries (source_id NULL) are excluded.
        sql = f"""
            SELECT e.*, snippet(kb_fts, 0, '[', ']', '...', 8) AS snippet,
                   bm25(kb_fts) AS rank
            FROM kb_fts
            JOIN kb_entries e ON e.id = kb_fts.rowid
            JOIN kb_sources s ON s.id = e.source_id
            WHERE kb_fts MATCH ?
              AND s.source_type IN ({placeholders})
            ORDER BY rank
            LIMIT ?
        """
        params: list = [query, *source_types, limit]
    else:
        sql = """
            SELECT e.*, snippet(kb_fts, 0, '[', ']', '...', 8) AS snippet,
                   bm25(kb_fts) AS rank
            FROM kb_fts
            JOIN kb_entries e ON e.id = kb_fts.rowid
            WHERE kb_fts MATCH ?
            ORDER BY rank
            LIMIT ?
        """
        params = [query, limit]

    cur.execute(sql, params)
    rows = cur.fetchall()
    conn.close()
    return [_row_to_dict(r) for r in rows]


@mcp.tool()
def kb_add(
    content: str,
    entry_type: str,
    tags: list[str] | None = None,
    source_id: int | None = None,
    created_by: str = "agent",
) -> dict:
    """Add a KB entry. Returns the new entry id and current state.

    For MVP, all agent-written entries are created with status='pending'
    (Level 0 trust). Customer-written entries are created with
    status='approved' (Level 3 trust — they wrote it, they own it).

    Args:
        content: the runbook/fact/gotcha text.
        entry_type: one of 'runbook', 'fact', 'gotcha'.
        tags: optional list of tag strings; stored as a JSON array.
        source_id: optional FK to kb_sources.id.
        created_by: 'agent' (default) or 'customer'.
    """
    if entry_type not in VALID_ENTRY_TYPES:
        return {"error": f"entry_type must be one of {VALID_ENTRY_TYPES}"}
    if created_by not in VALID_CREATED_BY:
        return {"error": f"created_by must be one of {VALID_CREATED_BY}"}

    # Customer-written entries are auto-approved; agents always start
    # at pending.
    initial_status = "approved" if created_by == "customer" else "pending"
    # Mirror the trust ladder: customer=3, agent=0. K6 can add intermediate
    # levels (e.g., 'approved_agent') later without breaking the schema.
    initial_trust = 3 if created_by == "customer" else 0

    tags_json = json.dumps(tags) if tags else None

    conn = _connect()
    cur = conn.cursor()
    if source_id is not None:
        cur.execute(
            """
            INSERT INTO kb_entries
                (source_id, entry_type, content, tags, created_by, status, trust_level_at_creation)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """,
            (source_id, entry_type, content, tags_json, created_by, initial_status, initial_trust),
        )
    else:
        cur.execute(
            """
            INSERT INTO kb_entries
                (entry_type, content, tags, created_by, status, trust_level_at_creation)
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (entry_type, content, tags_json, created_by, initial_status, initial_trust),
        )
    new_id = cur.lastrowid
    conn.commit()
    cur.execute("SELECT * FROM kb_entries WHERE id=?", (new_id,))
    row = cur.fetchone()
    conn.close()
    return _row_to_dict(row)


@mcp.tool()
def kb_update(
    entry_id: int,
    content: str | None = None,
    tags: list[str] | None = None,
    status: str | None = None,
) -> dict:
    """Update an existing KB entry.

    Args:
        entry_id: required. The id of the entry to update.
        content: new content (if changing).
        tags: new tags list (replaces existing).
        status: new status. Customer flips pending -> approved/rejected.

    Returns the updated row, or {'error': 'not found'} if entry_id is
    unknown, or {'error': 'no fields to update'} if nothing was passed.
    """
    if status is not None and status not in VALID_STATUSES:
        return {"error": f"status must be one of {VALID_STATUSES}"}

    conn = _connect()
    cur = conn.cursor()
    cur.execute("SELECT * FROM kb_entries WHERE id=?", (entry_id,))
    if cur.fetchone() is None:
        conn.close()
        return {"error": "not found", "entry_id": entry_id}

    updates: dict = {}
    if content is not None:
        updates["content"] = content
    if tags is not None:
        updates["tags"] = json.dumps(tags)
    if status is not None:
        updates["status"] = status

    if not updates:
        conn.close()
        return {"error": "no fields to update"}

    updates["updated_at"] = "CURRENT_TIMESTAMP"
    set_clause = ", ".join(f"{k}=?" for k in updates.keys())
    values = list(updates.values()) + [entry_id]
    cur.execute(
        f"UPDATE kb_entries SET {set_clause} WHERE id=?",
        values,
    )
    conn.commit()
    cur.execute("SELECT * FROM kb_entries WHERE id=?", (entry_id,))
    row = cur.fetchone()
    conn.close()
    return _row_to_dict(row)


@mcp.tool()
def kb_list(
    source_type: str | None = None,
    status: str | None = None,
    limit: int = 50,
    offset: int = 0,
) -> list[dict]:
    """List KB entries, optionally filtered. For the review queue UI.

    Args:
        source_type: optional filter — restrict to entries whose source has
            this source_type. Entries with no source (source_id NULL) are
            always included.
        status: optional filter — restrict to this status.
        limit: max rows (default 50).
        offset: for pagination.
    """
    if source_type is not None and source_type not in VALID_SOURCE_TYPES:
        return [{"error": f"invalid source_type: {source_type}"}]
    if status is not None and status not in VALID_STATUSES:
        return [{"error": f"invalid status: {status}"}]

    conn = _connect()
    cur = conn.cursor()
    # When source_type is set, INNER JOIN so we only return entries that
    # came from a matching source. When source_type is NOT set, LEFT JOIN
    # so sourceless entries (source_id NULL) are included in the listing.
    if source_type is not None:
        sql = """
            SELECT e.*
            FROM kb_entries e
            JOIN kb_sources s ON s.id = e.source_id
            WHERE 1=1
        """
    else:
        sql = """
            SELECT e.*
            FROM kb_entries e
            LEFT JOIN kb_sources s ON s.id = e.source_id
            WHERE 1=1
        """
    params: list = []
    if source_type is not None:
        sql += " AND s.source_type = ?"
        params.append(source_type)
    if status is not None:
        sql += " AND e.status = ?"
        params.append(status)
    sql += " ORDER BY e.id DESC LIMIT ? OFFSET ?"
    params.extend([limit, offset])
    cur.execute(sql, params)
    rows = cur.fetchall()
    conn.close()
    return [_row_to_dict(r) for r in rows]


@mcp.tool()
def kb_delete(entry_id: int) -> dict:
    """Delete a KB entry. Returns the deleted entry contents.

    DESTRUCTIVE — the row is permanently removed (and the FTS index
    is updated via the kb_ad trigger). Callers should always confirm
    with the user before invoking this.
    """
    conn = _connect()
    cur = conn.cursor()
    cur.execute("SELECT * FROM kb_entries WHERE id=?", (entry_id,))
    row = cur.fetchone()
    if row is None:
        conn.close()
        return {"error": "not found", "entry_id": entry_id}
    deleted = _row_to_dict(row)
    cur.execute("DELETE FROM kb_entries WHERE id=?", (entry_id,))
    conn.commit()
    rows_affected = cur.rowcount
    conn.close()
    return {
        "status": "deleted",
        "entry_id": entry_id,
        "rows": rows_affected,
        "deleted_record": deleted,
    }


# ---------------------------------------------------------------------------
# Optional convenience tools: source management.
# Useful for K2 (bootstrap ingestion) and K3 (review queue UI).
# ---------------------------------------------------------------------------


@mcp.tool()
def kb_add_source(
    name: str, source_type: str, file_path_or_url: str | None = None
) -> dict:
    """Add a KB source (where knowledge chunks came from).

    Args:
        name: human-readable name (e.g., "OpenWrt firewall runbook").
        source_type: one of 'skill', 'customer_doc', 'runtime'.
        file_path_or_url: optional path or URL for traceability.
    """
    if source_type not in VALID_SOURCE_TYPES:
        return {"error": f"source_type must be one of {VALID_SOURCE_TYPES}"}
    conn = _connect()
    cur = conn.cursor()
    cur.execute(
        "INSERT INTO kb_sources (name, source_type, file_path_or_url) VALUES (?, ?, ?)",
        (name, source_type, file_path_or_url),
    )
    new_id = cur.lastrowid
    conn.commit()
    cur.execute("SELECT * FROM kb_sources WHERE id=?", (new_id,))
    row = cur.fetchone()
    conn.close()
    return dict(row)


@mcp.tool()
def kb_list_sources() -> list[dict]:
    """List all KB sources, newest first."""
    conn = _connect()
    cur = conn.cursor()
    cur.execute("SELECT * FROM kb_sources ORDER BY id DESC")
    rows = cur.fetchall()
    conn.close()
    return [dict(r) for r in rows]


def main() -> None:
    parser = argparse.ArgumentParser(description="AIAMSBS kb-mcp server")
    parser.add_argument("--host", default="0.0.0.0", help="bind host (default 0.0.0.0)")
    parser.add_argument("--port", type=int, default=8002, help="bind port (default 8002)")
    args = parser.parse_args()

    init_db()

    # FastMCP.run() does not accept host/port kwargs in this version — set
    # via the settings object (host/port are top-level Settings fields).
    mcp.settings.host = args.host
    mcp.settings.port = args.port
    mcp.run(transport="streamable-http")


if __name__ == "__main__":
    main()
