{
 "title": "All Discovered Devices-Up/Down",
 "tags": [
  "adminlm",
  "inventory",
  "blackbox"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Device",
    "query": {
     "query": "label_values(probe_success{job=\"blackbox_inventory\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total devices",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{job=\"blackbox_inventory\"})"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=\"blackbox_inventory\"} == 1)"
    }
   ]
  },
  {
   "title": "Down",
   "type": "stat",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{job=\"blackbox_inventory\"} == 0)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 24, "h": 2 },
   "repeat": "instance",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox_inventory\", instance=~\"$instance\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}